name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue, needs attention'
        stale-pr-message: 'Stale pull request, review files'
        stale-issue-label: 'no activity on an issue, please attend to it'
        stale-pr-label: 'no activity on a pull request, please attend to it'
